spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/testbit
spring.datasource.username=postgres
spring.datasource.password=RaFF431

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always
